Ft/openAfrica API integration
CodeForAfrica/ui pull request #412
Opened 2023-04-18 09:42 UTC by kelvinkipruto

## Description

This PR adds the feature to fetch documents from [openAfrica](https://openafrica.net/).

Fixes #411

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2023-04-18 11:20 UTC, koechkevin requested changes

2023-04-18 11:20 UTC, koechkevin commented on apps/charterafrica/src/pages/api/v1/data/datasets.js
> +  return res.json(404).json({ message: "NO ORGANIZATION PROVIDED" });
```suggestion
  return res.status(404).json({ message: "NO ORGANIZATION PROVIDED" });
```

2023-04-18 11:23 UTC, koechkevin reviewed
Overall, the code appears to be well-structured and follows best practices for handling API requests and responses.

2023-04-18 11:49 UTC, kilemensi reviewed
👍🏽 

---

Haven't run it locally but I'm iffy about 2 things:
1. Why do we need the front-end to send the `organisation` via `v1/data/datasets`? I'm assuming we don't want this to change i.e. it should always point to the one set in the CMS.
2. Don't see anywhere we're handling pagination.

2023-04-19 08:52 UTC, koechkevin approved these changes

2023-04-20 06:36 UTC, kilemensi commented
> 👍🏽
> 
> Haven't run it locally but I'm iffy about 2 things:
> 
>     1. Why do we need the front-end to send the `organisation` via `v1/data/datasets`? I'm assuming we don't want this to change i.e. it should always point to the one set in the CMS.
> 

Heita @kelvinkipruto .

Where are we addressing point 1 above? i.e. pull organisation id from the CMS and use it for searching. Was hoping to see it somewhere in `src/lib/openafrica`

2023-04-20 09:13 UTC, kilemensi commented
@kelvinkipruto ?

2023-04-20 09:25 UTC, kelvinkipruto commented
@kilemensi Sorry I was updating how it fetches `tags`
In my design approach `src/lib/openafrica` should only interact with `openAfrica API` and not with the CMS. Getting data from CMS should be handled similarly to how we do in `sourceAfrica`. I have this [file](https://github.com/CodeForAfrica/ui/blob/f0eccf2697a34a474e84a1542ecfcbac211671f4/apps/charterafrica/src/lib/data/common/processPageDatasets.js) to show how we can handle it.
The organization will be passed to the component as [props](https://github.com/CodeForAfrica/ui/blob/e64e9666ec419163ed871078c81071cebc91ad55/apps/charterafrica/src/lib/data/common/processPageDatasets.js#L19) which we can then use when making API calls to `v1/data/datasets`

2023-04-20 09:52 UTC, kelvinkipruto commented
@kilemensi We [only fetch data](https://github.com/CodeForAfrica/ui/blob/e64e9666ec419163ed871078c81071cebc91ad55/apps/charterafrica/src/lib/data/common/processPageDatasets.js#L8-L9) if we have an `organization` provided in the CMS. The `organizationId` is required, so we're guaranteed to always have an organization to fetch data from. So yes, we can fetch data from any organization that is set up in the CMS.

2023-04-20 09:57 UTC, kilemensi commented
> @kilemensi We [only fetch data](https://github.com/CodeForAfrica/ui/blob/e64e9666ec419163ed871078c81071cebc91ad55/apps/charterafrica/src/lib/data/common/processPageDatasets.js#L8-L9) if we have an `organization` provided in the CMS. The `organizationId` is required, so we're guaranteed to always have an organization to fetch data from. So yes, we can fetch data from any organization that is set up in the CMS.

@kelvinkipruto I mean the API accepts **any** organisation not necessarily the one set in the CMS.

2023-04-20 10:07 UTC, kelvinkipruto commented
@kilemensi Yes, now I get you. The API will accept any organization passed to it.
Given that I have set the `datasets` as a page block, it would be difficult to fetch the `organizationId` from `src/lib/openafrica`. To solve it perhaps I could set datasets as a `collection`. This will make it possible to fetch the collection, hence the organization easily

2023-04-24 13:10 UTC, kelvinkipruto commented
@kilemensi I have updated it.

2023-04-24 13:29 UTC, kilemensi commented on apps/charterafrica/src/lib/data/rest/index.js
> +
Not sure this is necessary... both pages via lib/data and APIs have access to `payload` object and can hence fetch the organisation `id`/`slug` _**before**_ passing it to `openAfrica` lib.

The `openAfrica` lib shouldn't need to know anything about data/rest, etc.

2023-04-24 13:29 UTC, kilemensi commented on apps/charterafrica/src/lib/data/common/processPageDatasets.js
> +
```suggestion
```

2023-04-24 13:29 UTC, kilemensi commented on apps/charterafrica/src/lib/data/common/processPageDatasets.js
> +
```suggestion
```

2023-04-27 07:47 UTC, kilemensi reviewed
🚀

2023-04-27 10:55 UTC, merged