ft/add-google-analytics
CodeForAfrica/ui pull request #482
Opened 2023-07-11 07:52 UTC by kelvinkipruto

## Description

Add Google Analytics to cfa site

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2023-07-12 04:04 UTC, thepsalmist approved these changes

2023-07-12 05:07 UTC, kilemensi requested changes
👍🏽 

----

You still need to handle routing/page change events. See the provided [example](https://github.com/vercel/next.js/blob/b9760b2910c720ee0b4700917cd02575f6bbd7d6/examples/with-google-analytics/pages/_app.js#L8-L35).

2023-07-12 05:07 UTC, kilemensi commented on apps/codeforafrica/src/pages/_app.page.js
> +        strategy="lazyOnload"
```suggestion
```

Should use `afterInteractive` (the default strategy) for analytics. [Docs](https://nextjs.org/docs/app/api-reference/components/script#afterinteractive).

2023-07-13 13:13 UTC, kilemensi approved these changes
🚀

2023-07-14 06:42 UTC, merged